-- MySQL Script generated by MySQL Workbench
-- sam. 01 févr. 2020 13:21:24 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema raspberry_eleves
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema raspberry_eleves
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `raspberry_eleves` DEFAULT CHARACTER SET utf8 ;
USE `raspberry_eleves` ;

-- -----------------------------------------------------
-- Table `raspberry_eleves`.`Classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raspberry_eleves`.`Classes` ;

CREATE TABLE IF NOT EXISTS `raspberry_eleves`.`Classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `raspberry_eleves`.`eleves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raspberry_eleves`.`eleves` ;

CREATE TABLE IF NOT EXISTS `raspberry_eleves`.`eleves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `photo` VARCHAR(255) NULL,
  `id_classe` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eleves_1_idx` (`id_classe` ASC) VISIBLE,
  CONSTRAINT `fk_eleves_1`
    FOREIGN KEY (`id_classe`)
    REFERENCES `raspberry_eleves`.`Classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `raspberry_eleves`.`entree_eleve`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raspberry_eleves`.`entree_eleve` ;

CREATE TABLE IF NOT EXISTS `raspberry_eleves`.`entree_eleve` (
  `idE` INT NULL,
  `h_entree` VARCHAR(45) NULL,
  INDEX `fk_entree_eleve_1_idx` (`idE` ASC) VISIBLE,
  CONSTRAINT `fk_entree_eleve_1`
    FOREIGN KEY (`idE`)
    REFERENCES `raspberry_eleves`.`eleves` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `raspberry_eleves`.`horaire_cours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raspberry_eleves`.`horaire_cours` ;

CREATE TABLE IF NOT EXISTS `raspberry_eleves`.`horaire_cours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `h_debut` VARCHAR(45) NULL,
  `h_fin` VARCHAR(45) NULL,
  `id_classe` INT NULL,
  `nom_prof` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horaire_cours_1_idx` (`id_classe` ASC) VISIBLE,
  CONSTRAINT `fk_horaire_cours_1`
    FOREIGN KEY (`id_classe`)
    REFERENCES `raspberry_eleves`.`Classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `raspberry_eleves` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

USE `raspberry_eleves`;
DROP  IF EXISTS `raspberry_eleves`.`routine1`;

DELIMITER $$
USE `raspberry_eleves`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
